version: "3"

services: 
    mongo: 
        restart: always
        image: mongo
        command: --quiet
        volumes:
          - ../../data:/data/db
        ports:
          - "27017:27017"
        networks:
          - todo
    todo: 
        restart: always
        build:
            context: ../../ 
            dockerfile: ./deployment/dev/dev.Dockerfile
        env_file: ../../config/env/dev.env
        ports:
            - 8000:8000
        networks:
            - todo
        volumes:
            - ../../:/home/cccuong/todo/
            - ignore:/home/cccuong/todo/node_modules/
        links:
            - mongo
        depends_on:
            - mongo

networks:
    todo:
        external: true

volumes:
    data:
    ignore:



